
!if "$(DDK_TARGET_OS)"=="WinXP" && "$(_BUILDARCH)"=="IA64"
!message To build a filter for the XP 64-bit platform, please use the appropriate Server 2003 64-bit build environment.
!else
!INCLUDE $(NTMAKEENV)\makefile.def
!endif

