#include <winsock2.h>
#include <windows.h>
#include <time.h>
#include "ntdll.h"

typedef BOOL (WINAPI* ENUMSERVICESSTATUSA)(SC_HANDLE,DWORD,DWORD,LPENUM_SERVICE_STATUS,DWORD,LPDWORD,LPDWORD,LPDWORD);

#ifndef __ENUMSERVICESSTATUSA__
#define __ENUMSERVICESSTATUSA__

ENUMSERVICESSTATUSA OldEnumServicesStatusA;
BOOL WINAPI NewEnumServicesStatusA(SC_HANDLE,DWORD,DWORD,LPENUM_SERVICE_STATUS,DWORD,LPDWORD,LPDWORD,LPDWORD);

#endif 