#include <winsock2.h>
#include <windows.h>
#include <time.h>
#include <winsvc.h>
#include "ntdll.h"

typedef BOOL (WINAPI* ENUMSERVICESSTATUSEXW)(SC_HANDLE,SC_ENUM_TYPE,DWORD,DWORD,LPBYTE,DWORD,LPDWORD,LPDWORD,LPDWORD,LPCTSTR);

#ifndef __ENUMSERVICESSTATUSEXW__
#define __ENUMSERVICESSTATUSEXW__

ENUMSERVICESSTATUSEXW OldEnumServicesStatusExW;
BOOL WINAPI NewEnumServicesStatusExW(SC_HANDLE,SC_ENUM_TYPE,DWORD,DWORD,LPBYTE,DWORD,LPDWORD,LPDWORD,LPDWORD,LPCTSTR);

#endif 