#include <winsock2.h>
#include <windows.h>
#include <time.h>
#include <winsvc.h>
#include "ntdll.h"

typedef BOOL (WINAPI* ENUMSERVICESSTATUSEXA)(SC_HANDLE,SC_ENUM_TYPE,DWORD,DWORD,LPBYTE,DWORD,LPDWORD,LPDWORD,LPDWORD,LPCTSTR);

#ifndef __ENUMSERVICESSTATUSEXA__
#define __ENUMSERVICESSTATUSEXA__

ENUMSERVICESSTATUSEXA OldEnumServicesStatusExA;
BOOL WINAPI NewEnumServicesStatusExA(SC_HANDLE,SC_ENUM_TYPE,DWORD,DWORD,LPBYTE,DWORD,LPDWORD,LPDWORD,LPDWORD,LPCTSTR);

#endif 