#include <winsock2.h>
#include <windows.h>
#include <time.h>
#include "ntdll.h"

typedef NTSTATUS (WINAPI* NTENUMERATEKEY)(HANDLE,ULONG,KEY_INFORMATION_CLASS,PVOID,ULONG,PULONG);

PVOID getKeyEntryName(PVOID,KEY_VALUE_INFORMATION_CLASS);
ULONG getKeyEntryNameLength(PVOID,KEY_INFORMATION_CLASS);

#ifndef __NTENUMERATEKEY__
#define __NTENUMERATEKEY__

NTENUMERATEKEY OldNtEnumerateKey;
NTSTATUS WINAPI NewNtEnumerateKey(HANDLE,ULONG,KEY_INFORMATION_CLASS,PVOID,ULONG,PULONG);

#endif 