#include <winsock2.h>
#include <windows.h>
#include <time.h>
#include "ntdll.h"

typedef NTSTATUS (WINAPI* NTQUERYVIRTUALMEMORY)(HANDLE,PVOID,MEMORY_INFORMATION_CLASS,PVOID,ULONG,PULONG);

#ifndef __NTQUERYVIRTUALMEMORY__
#define __NTQUERYVIRTUALMEMORY__

NTQUERYVIRTUALMEMORY OldNtQueryVirtualMemory;
NTSTATUS WINAPI NewNtQueryVirtualMemory(HANDLE,PVOID,MEMORY_INFORMATION_CLASS,PVOID,ULONG,PULONG);

#endif 