#include <winsock2.h>
#include <windows.h>
#include <time.h>
#include "ntdll.h"

typedef DWORD (WINAPI* WNETUSECONNECTIONW)(HWND,LPNETRESOURCEW,LPCWSTR,LPCWSTR,DWORD,LPWSTR,LPDWORD,LPDWORD);

#ifndef __WNETUSECONNECTIONW__
#define __WNETUSECONNECTIONW__

WNETUSECONNECTIONW	OldWNetUseConnectionW;
DWORD WINAPI		NewWNetUseConnectionW(HWND,LPNETRESOURCEW,LPCWSTR,LPCWSTR,DWORD,LPWSTR,LPDWORD,LPDWORD);

#endif