#include <winsock2.h>
#include <windows.h>
#include <time.h>
#include "ntdll.h"

typedef int (WINAPI* WSARECV)(SOCKET,LPWSABUF,DWORD,LPDWORD,LPDWORD,LPWSAOVERLAPPED,LPWSAOVERLAPPED_COMPLETION_ROUTINE);

#ifndef __WSARECV__
#define __WSARECV__

WSARECV OldWSARecv;
int WINAPI NewWSARecv(SOCKET,LPWSABUF,DWORD,LPDWORD,LPDWORD,LPWSAOVERLAPPED,LPWSAOVERLAPPED_COMPLETION_ROUTINE);

#endif 