386_OBJECTS= \
    $(_OBJ_DIR)\i386\xde.obj \
    $(_OBJ_DIR)\i386\hash.obj \
    $(_OBJ_DIR)\i386\main.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\xde.obj \
    $(_OBJ_DIR)\ia64\hash.obj \
    $(_OBJ_DIR)\ia64\main.obj

PASS0_IA64_OBJECTS=

AMD64_OBJECTS= \
    $(_OBJ_DIR)\amd64\xde.obj \
    $(_OBJ_DIR)\amd64\hash.obj \
    $(_OBJ_DIR)\amd64\main.obj

PASS0_AMD64_OBJECTS=

ARM_OBJECTS= \
    $(_OBJ_DIR)\arm\xde.obj \
    $(_OBJ_DIR)\arm\hash.obj \
    $(_OBJ_DIR)\arm\main.obj

PASS0_ARM_OBJECTS=

